name: Android Build



on:
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Write permissions for Gradlew
        run: chmod +x ./gradlew

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: Build Project
        run: ./gradlew buildDevDebug