name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-varsion: 11

      - name: Run tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble