name: Android Build

on: pull_request

jobs:

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew test

  build:
    needs: [ unit_tests ]
    runs-on: ubuntu-latest
    steps:

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build Project
        run: ./gradlew build